name: Integration Idea
description: Idea for improving Lyrasis CST interoperability.
title: "💡 Idea: [short phrase] "
labels: ["idea"]
projects: ["lyrasisorghome/projects/1"]
type: solution

body:
- type: markdown
  attributes:
    value: | 
      # Call to Action
      An interoperability solution has been proposed. Please discuss this idea further. Some prompts to guide you:
      - What would this solution achieve? Who would use it and why?
      - If there are applications involved, what are they? Which components of each application would you like to integrate, and for what purpose?
      - Describe the user journey as you imagine using this integration. Start by filling in the blanks: As a [role], I want to [discrete function].
       
      ## What happens next?
      Comment on this issue by ==January 15== if you would like for this integration to be considered for the roadmap! See the Feedback[link] page for more information about the feedback process.
      Thank you for participating in the Lyrasis CST Interoperability project!
       
- type: checkboxes
  id: CST
  attributes:
    label: Which Lyrasis CST(s) does this interoperability solution involve?
    description: You must select at least one.
    options:
      - label: ArchivesSpace
      - label: CollectionSpace
      - label: DSpace
      - label: Fedora
      - label: VIVO
  validations:
    required: true

- type: input
  id: solution-summary
  attributes:
    label: Idea
    placeholder: An integration/interoperabilty project for/between [Application/CST] and [Application/CST] to [general description of purpose]
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: More information
    description: Any background information, such as where the idea came from or why it would benefit the CST.
    placeholder: 
  validations:
    required: false

- type: input
  id: groups-link
  attributes:
    label: Discussion on Google groups
    description: Link to the discussion on Google groups
    placeholder: https://groups.google.com/a/lyrasislists.org/g/cst-interoperability
  validations:
    required: false

- type: textarea
  id: user-story
  attributes:
    label: User story
    description: Share some more detail about your workflow and what is important in designing the integration.
  validations:
    required: false
